version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
current:
  spec: .specwright/specs/cockpit-scripts-to-verbs.md
  aip: .specwright/aips/cockpit-scripts-to-verbs.yaml
