version: '0.1'
paths:
  specs: .specwright/specs
  aips: .specwright/aips
repo:
  default_branch: main
user:
  default_owner: null
current:
  spec: .specwright/specs/job-runner-spec.md
  aip: /workspace/life-cli/.specwright/aips/job-runner-spec.yaml
