jobs:
  pipeline.ingest:
    description: "Run ingestion pipeline"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.ingest"
          dry_run: "{dry_run}"
          verbose: "{verbose}"

  pipeline.canonize:
    description: "Run canonization pipeline"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.canonize"
          dry_run: "{dry_run}"
          verbose: "{verbose}"

  pipeline.formation:
    description: "Run formation pipeline"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.formation"
          dry_run: "{dry_run}"
          verbose: "{verbose}"

  pipeline.project:
    description: "Run local projection pipeline"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.project"
          dry_run: "{dry_run}"
          verbose: "{verbose}"

  pipeline.views:
    description: "Create BigQuery projection views"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.views"
          dry_run: "{dry_run}"
          verbose: "{verbose}"

  pipeline.run_all:
    description: "Run full daily pipeline"
    steps:
      - name: run
        call: life_jobs.pipeline.run_lorchestra
        args:
          job_id: "pipeline.daily_all"
          dry_run: "{dry_run}"
          verbose: "{verbose}"
