# Microsoft Graph job definitions
# Copy to ~/.life/jobs/graph.yaml

jobs:
  fetch_recent_mail:
    description: "Fetch recent emails"
    steps:
      - name: fetch
        call: life_jobs.graph.get_messages
        args:
          account: personal
          top: 50
          select: [id, subject, from, receivedDateTime]
          output: ~/data/emails.json

  fetch_unread_mail:
    description: "Fetch unread emails"
    steps:
      - name: fetch
        call: life_jobs.graph.get_messages
        args:
          account: personal
          top: 100
          filter: "isRead eq false"
          output: ~/data/unread_emails.json

  send_test_email:
    description: "Send a test email"
    steps:
      - name: send
        call: life_jobs.graph.send_mail
        args:
          account: drben
          to: ["{recipient}"]
          subject: "Test from life-cli"
          body: "This is a test email sent via life run."

  whoami:
    description: "Get current user profile"
    steps:
      - name: me
        call: life_jobs.graph.me
        args:
          account: personal

  fetch_calendar:
    description: "Fetch upcoming calendar events"
    steps:
      - name: fetch
        call: life_jobs.graph.get_calendar_events
        args:
          account: personal
          top: 20
          select: [subject, start, end, location]
          output: ~/data/calendar.json

  list_onedrive:
    description: "List OneDrive root files"
    steps:
      - name: list
        call: life_jobs.graph.get_files
        args:
          account: personal
          output: ~/data/onedrive_files.json
