# Multi-step workflow job definitions
# Copy to ~/.life/jobs/workflows.yaml

jobs:
  daily_data_pull:
    description: "Pull daily data from multiple sources"
    steps:
      - name: contacts
        call: life_jobs.dataverse.query
        args:
          account: lifeos
          entity: contacts
          filter: "statecode eq 0"
          output: ~/data/contacts.json

      - name: emails
        call: life_jobs.graph.get_messages
        args:
          account: personal
          top: 50
          output: ~/data/emails.json

      - name: calendar
        call: life_jobs.graph.get_calendar_events
        args:
          account: personal
          top: 10
          output: ~/data/calendar.json

  backup_scripts:
    description: "Run backup script (example shell step)"
    steps:
      - name: backup
        call: life_jobs.shell.run
        args:
          command: "tar -czf ~/backups/scripts-$(date +%Y%m%d).tar.gz ~/scripts"
          timeout: 60
